Fix preg line return
Nexylan/PHPAV pull request #22
Opened 2016-12-16 14:52 UTC by gallart

2016-12-16 15:28 UTC, soullivaneuh requested changes

2016-12-16 15:28 UTC, Soullivaneuh commented on data/webshells.txt
> +\$GLOBALS\[\$GLOBALS\['
I don't think this is part of the preg_line fix.

What is it? This should be on a separated commit.

2016-12-16 15:28 UTC, Soullivaneuh commented on scan.php
> -                        if (preg_match("/\.php$/", $file)) { // Currently only selects PHP scripts for scanning
This tab correction must be on a separated commit.

2016-12-18 20:49 UTC, gallart commented on scan.php
> -                        if (preg_match("/\.php$/", $file)) { // Currently only selects PHP scripts for scanning
Don't know how to fix that.

2016-12-19 08:53 UTC, Soullivaneuh commented on scan.php
> -                        if (preg_match("/\.php$/", $file)) { // Currently only selects PHP scripts for scanning
As usual: Undo your commit. Add your tab modification with `git add --patch`, commit, then commit again for the rest. ;-)

2016-12-19 21:01 UTC, closed without merging